name: ayan_healthcare
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: any
  json_annotation: any
  freezed_annotation: any
  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  get: ^4.6.1
  intl: ^0.19.0
  fluttertoast: ^8.2.10
  url_launcher: ^6.3.1
  whatsapp_unilink: ^2.1.0
  flare_loading: ^3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  youtube_player_iframe: ^5.1.5
  percent_indicator: ^4.2.4
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.17
  patrol: ^3.11.1
  photo_view: ^0.15.0
  google_fonts: ^6.2.1
  flutter_holo_date_picker: ^2.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  local_auth: ^2.0.0
  flutter_inappwebview: ^6.0.0
  flare_flutter: ^3.0.2
  http: ^1.2.0
  flutter_cached_pdfview: ^0.4.3
  image: ^4.2.0
  path_provider: ^2.1.5
  firebase_core: ^2.24.2
  dio: ^5.8.0
  chucker_flutter: ^1.6.3
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.5.5
  provider: ^6.1.1
  uuid: ^4.2.2
  flutter_chat_types: ^3.0.0
  crypto: ^3.0.1
  flutter_firebase_chat_core: ^1.6.7
  open_filex: ^4.6.0
  flutter_chat_ui: ^1.6.15
  firebase_messaging: ^14.7.10
  encrypt: ^5.0.3
  cloud_functions: ^4.7.6
  flutter_speed_dial: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_runner: any
  freezed: any
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/banners/
    - assets/icons/
    - assets/icons/icons/
    - assets/animation/
    - assets/logo/
  
  # Uncomment and modify the following section if you want to use custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true