// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUBfsLhH9g9EYZ5vGMf83-L64yCOj2AbM',
    appId: '1:410355883221:web:7a39ea6e46d5536664965c',
    messagingSenderId: '410355883221',
    projectId: 'ayan-healthcare',
    authDomain: 'ayan-healthcare.firebaseapp.com',
    storageBucket: 'ayan-healthcare.firebasestorage.app',
    measurementId: 'G-T0EDBSTRG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB2zTnD43u_OckYwtjIKLlFh6bT8cQXN8',
    appId: '1:410355883221:android:83eaff8925dd349c64965c',
    messagingSenderId: '410355883221',
    projectId: 'ayan-healthcare',
    storageBucket: 'ayan-healthcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxG-mLMXvXM6VMlSzt3nnrTi2fCgXmAJw',
    appId: '1:410355883221:ios:47516fc3509c344a64965c',
    messagingSenderId: '410355883221',
    projectId: 'ayan-healthcare',
    storageBucket: 'ayan-healthcare.firebasestorage.app',
    iosBundleId: 'com.instacare.ayanHealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxG-mLMXvXM6VMlSzt3nnrTi2fCgXmAJw',
    appId: '1:410355883221:ios:47516fc3509c344a64965c',
    messagingSenderId: '410355883221',
    projectId: 'ayan-healthcare',
    storageBucket: 'ayan-healthcare.firebasestorage.app',
    iosBundleId: 'com.instacare.ayanHealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUBfsLhH9g9EYZ5vGMf83-L64yCOj2AbM',
    appId: '1:410355883221:web:45cce9ce8923917e64965c',
    messagingSenderId: '410355883221',
    projectId: 'ayan-healthcare',
    authDomain: 'ayan-healthcare.firebaseapp.com',
    storageBucket: 'ayan-healthcare.firebasestorage.app',
    measurementId: 'G-WF3T4QETLW',
  );
}
